# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown

google_analytics: Subin Abid | Blog
title: Subin Abid

defaults:
  -
    scope:
      path: "" # empty string for all files
      values:
      title: Subin Abid | Blog

description: Subin Abid's blog
author:
  name: Subin Abid
  email: me@sabid.in
  github: subinabid
  mmastodon: mas.to/@sabid
  linkedin: subinabid
  bio: Engineer, Project Manager, Super Dad, Guitarist, Photographer, Bibliophile </br></br></br> Author is a Project Manager at NTPC Ltd.</br> Former Business Analyst at Mu Sigma, Product Development Engineer at M&M 
  email_md5: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

gems:
  - jekyll-paginate
