# Welcome to Jekyll!

# Site settings
title: Subin Abid | Blog
email: mail@subinabid.xyz

description: >
  Subin Abid's personal blog

baseurl: ""
url: "http://subinabid.github.io/blog"
username: subinabid

# Build settings
markdown: kramdown

gems:
  - jemoji
